name: daily-cron
on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call email digest API
        run: |
          curl --request GET \
          --url 'https://hacker-news-delta.vercel.app/api/email-digest' \
          --header 'Authorization: Bearer a1ls2kd3jf4hg5g'
